# Pythonのイメージを指定
FROM python:3.13
# PYTHONDONTWRITEBYTECODEとPYTHONUNBUFFEREDはオプション
# pycファイル(および__pycache__)の生成を行わないようにする
ENV PYTHONDONTWRITEBYTECODE=1
# 標準出力・標準エラーのストリームのバッファリングを行わない
ENV PYTHONUNBUFFERED=1
# 環境変数を設定
ENV DJANGO_SETTINGS_MODULE=mysite.settings

# Pythonパスを設定
ENV PYTHONPATH=/app

# 必要なシステムパッケージをインストール
RUN apt-get update && apt-get install -y \
  RUN pip install python-decouple \
  build-essential \
  libffi-dev \
  libssl-dev \
  libyaml-dev \
  gcc \
  python3-dev \
  && rm -rf /var/lib/apt/lists/*


# 作業ディレクトリを設定
WORKDIR /app

# 必要な依存パッケージをインストール
COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

# プロジェクト全体をコピー
COPY ../ /app/

# サーバーの起動
CMD ["gunicorn", "mysite.wsgi:application", "--bind", "0.0.0.0:8000"]
