# Pythonのイメージを指定
FROM python:3.13
# PYTHONDONTWRITEBYTECODEとPYTHONUNBUFFEREDはオプション
# pycファイル(および__pycache__)の生成を行わないようにする
ENV PYTHONDONTWRITEBYTECODE=1
# 標準出力・標準エラーのストリームのバッファリングを行わない
ENV PYTHONUNBUFFERED=1
# 環境変数を設定
ENV DJANGO_SETTINGS_MODULE=mysite.settings

RUN mkdir /code

# 必要なシステムパッケージをインストール
RUN apt-get update && apt-get install -y \
  build-essential \
  libffi-dev \
  libssl-dev \
  libyaml-dev \
  gcc \
  python3-dev \
  && rm -rf /var/lib/apt/lists/*

# コンテナのワークディレクトリを/codeに指定
WORKDIR /code
# ローカルのrequirements.txtをコンテナの/codeフォルダ直下に置く
COPY ./requirements.txt /code/
# コンテナ内でpip install -r requirements.txtを実行

RUN pip install -U pip setuptools wheel cython && pip install --no-cache-dir -r requirements.txt

# ソースコードをコンテナにコピー
COPY . /code/

# サーバーの起動
CMD ["gunicorn", "mysite.wsgi:application", "--bind", "0.0.0.0:8000"]
